service: tera-tech-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
      - arn:aws:dynamodb:ap-south-1:395706647357:table/contactTable
    
functions:
  contact:
    handler: src/contact.handler
    events:
      - httpApi:
          path: /
          method: post


resources:
  Resources:
    contactTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: contactTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

